#!/usr/bin/env python3
import os, sys

import os
_here = os.path.dirname(os.path.abspath(__file__))
_src  = os.path.join(_here, '..', 'src')
css_path = os.path.join(_src, 'fqcl_viz.css')
js_path  = os.path.join(_src, 'fqcl_viz.js')
out_path = '/maps/projects/fernandezguerra/apps/repos/fqdup/src/view_html_assets.hpp'

css = open(css_path).read()
js  = open(js_path).read()

def make_raw(content, varname):
    for delim in ['ASSET', 'FQDUP_ASSET', 'FQDUP_HTML_ASSET', 'RAWDELIM']:
        if f'){delim}' not in content:
            return f'static const char {varname}[] = R"{delim}(\n{content}\n){delim}";\n'
    raise ValueError("no safe raw string delimiter")

with open(out_path, 'w') as f:
    f.write('// AUTO-GENERATED by scripts/gen_html_assets.sh — do not edit by hand\n')
    f.write('#pragma once\n')
    f.write('#include <string_view>\n\n')
    f.write('namespace fqdup_html {\n\n')
    f.write(make_raw(css, 'CSS'))
    f.write('\n')
    f.write(make_raw(js, 'JS'))
    f.write('\n} // namespace fqdup_html\n')

print(f"wrote {out_path}  ({os.path.getsize(out_path)} bytes)")
